export const TIMEZONE_OPTIONS = [
  { value: "Pacific/Midway", label: "(UTC-11:00) Midway Island" },
  { value: "Pacific/Honolulu", label: "(UTC-10:00) Hawaii" },
  { value: "America/Anchorage", label: "(UTC-09:00) Alaska" },
  { value: "America/Los_Angeles", label: "(UTC-08:00) Pacific Time (US)" },
  { value: "America/Denver", label: "(UTC-07:00) Mountain Time (US)" },
  { value: "America/Chicago", label: "(UTC-06:00) Central Time (US)" },
  { value: "America/New_York", label: "(UTC-05:00) Eastern Time (US)" },
  { value: "America/Caracas", label: "(UTC-04:30) Caracas" },
  { value: "America/Halifax", label: "(UTC-04:00) Atlantic Time" },
  { value: "America/Manaus", label: "(UTC-04:00) Manaus" },
  { value: "America/Santiago", label: "(UTC-04:00) Santiago" },
  {
    value: "America/Argentina/Buenos_Aires",
    label: "(UTC-03:00) Buenos Aires",
  },
  { value: "America/Sao_Paulo", label: "(UTC-03:00) São Paulo" },
  { value: "America/Noronha", label: "(UTC-02:00) Mid-Atlantic" },
  { value: "Atlantic/Azores", label: "(UTC-01:00) Azores" },
  { value: "UTC", label: "(UTC+00:00) UTC" },
  { value: "Europe/London", label: "(UTC+00:00) London" },
  { value: "Europe/Paris", label: "(UTC+01:00) Paris" },
  { value: "Europe/Berlin", label: "(UTC+01:00) Berlin" },
  { value: "Europe/Madrid", label: "(UTC+01:00) Madrid" },
  { value: "Europe/Rome", label: "(UTC+01:00) Rome" },
  { value: "Europe/Amsterdam", label: "(UTC+01:00) Amsterdam" },
  { value: "Europe/Warsaw", label: "(UTC+01:00) Warsaw" },
  { value: "Europe/Athens", label: "(UTC+02:00) Athens" },
  { value: "Europe/Bucharest", label: "(UTC+02:00) Bucharest" },
  { value: "Africa/Cairo", label: "(UTC+02:00) Cairo" },
  { value: "Africa/Johannesburg", label: "(UTC+02:00) Johannesburg" },
  { value: "Europe/Helsinki", label: "(UTC+02:00) Helsinki" },
  { value: "Europe/Istanbul", label: "(UTC+03:00) Istanbul" },
  { value: "Europe/Moscow", label: "(UTC+03:00) Moscow" },
  { value: "Asia/Baghdad", label: "(UTC+03:00) Baghdad" },
  { value: "Africa/Nairobi", label: "(UTC+03:00) Nairobi" },
  { value: "Asia/Tehran", label: "(UTC+03:30) Tehran" },
  { value: "Asia/Dubai", label: "(UTC+04:00) Dubai" },
  { value: "Asia/Baku", label: "(UTC+04:00) Baku" },
  { value: "Asia/Karachi", label: "(UTC+05:00) Karachi" },
  { value: "Asia/Tashkent", label: "(UTC+05:00) Tashkent" },
  { value: "Asia/Kolkata", label: "(UTC+05:30) Kolkata" },
  { value: "Asia/Colombo", label: "(UTC+05:30) Colombo" },
  { value: "Asia/Dhaka", label: "(UTC+06:00) Dhaka" },
  { value: "Asia/Almaty", label: "(UTC+06:00) Almaty" },
  { value: "Asia/Bangkok", label: "(UTC+07:00) Bangkok" },
  { value: "Asia/Ho_Chi_Minh", label: "(UTC+07:00) Ho Chi Minh" },
  { value: "Asia/Jakarta", label: "(UTC+07:00) Jakarta" },
  { value: "Asia/Shanghai", label: "(UTC+08:00) Shanghai" },
  { value: "Asia/Singapore", label: "(UTC+08:00) Singapore" },
  { value: "Asia/Hong_Kong", label: "(UTC+08:00) Hong Kong" },
  { value: "Asia/Taipei", label: "(UTC+08:00) Taipei" },
  { value: "Asia/Perth", label: "(UTC+08:00) Perth" },
  { value: "Asia/Seoul", label: "(UTC+09:00) Seoul" },
  { value: "Asia/Tokyo", label: "(UTC+09:00) Tokyo" },
  { value: "Australia/Adelaide", label: "(UTC+09:30) Adelaide" },
  { value: "Australia/Sydney", label: "(UTC+10:00) Sydney" },
  { value: "Australia/Melbourne", label: "(UTC+10:00) Melbourne" },
  { value: "Pacific/Guam", label: "(UTC+10:00) Guam" },
  { value: "Pacific/Auckland", label: "(UTC+12:00) Auckland" },
  { value: "Pacific/Fiji", label: "(UTC+12:00) Fiji" },
] as const;

export const AVATAR_EMOJIS = [
  "😀",
  "😊",
  "😎",
  "🤩",
  "🥳",
  "😊",
  "😇",
  "🙂",
  "🧑",
  "👨",
  "👩",
  "🧑‍💻",
  "👨‍💼",
  "👩‍💼",
  "🧑‍🎓",
  "👨‍🎓",
  "🧑‍🔬",
  "👨‍🚀",
  "👩‍🎨",
  "🧑‍🍳",
  "👨‍⚕️",
  "👩‍🏫",
  "🦸",
  "🧑‍✈️",
  "🐱",
  "🐶",
  "🦊",
  "🐻",
  "🐼",
  "🦁",
  "🐸",
  "🦄",
  "🌸",
  "🌻",
  "🌺",
  "🍀",
  "⭐",
  "🔥",
  "💎",
  "🎯",
] as const;
