import { jsPDF } from "jspdf";
import { CURRENCY_SYMBOL } from "./categories";

interface ReportData {
  period: string;
  income: number;
  expenses: number;
  savings: number;
  transactions: Array<{
    description: string;
    amount: number;
    type: "income" | "expense";
    category: string;
    date: number;
  }>;
  habits: Array<{
    name: string;
    checkIns: number;
    streak: number;
  }>;
  tasks: {
    completed: number;
    total: number;
  };
  moods: Array<{
    mood: number;
    date: number;
  }>;
  focusMinutes: number;
}

export function generatePDFReport(data: ReportData): Blob {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("Pro Vision - Weekly Report", pageWidth / 2, 20, { align: "center" });

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(data.period, pageWidth / 2, 28, { align: "center" });

  doc.setDrawColor(99, 102, 241);
  doc.setLineWidth(0.5);
  doc.line(20, 32, pageWidth - 20, 32);

  let y = 45;

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Financial Summary", 20, y);
  y += 10;

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(`Income: ${CURRENCY_SYMBOL}${data.income.toLocaleString()}`, 25, y);
  y += 7;
  doc.text(`Expenses: ${CURRENCY_SYMBOL}${data.expenses.toLocaleString()}`, 25, y);
  y += 7;
  doc.setFont("helvetica", "bold");
  doc.text(`Net Savings: ${CURRENCY_SYMBOL}${data.savings.toLocaleString()}`, 25, y);
  y += 15;

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Category Breakdown", 20, y);
  y += 10;

  const categoryTotals: Record<string, number> = {};
  data.transactions
    .filter((t) => t.type === "expense")
    .forEach((t) => {
      categoryTotals[t.category] = (categoryTotals[t.category] || 0) + t.amount;
    });

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  Object.entries(categoryTotals)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 8)
    .forEach(([category, amount]) => {
      doc.text(`${category}: ${CURRENCY_SYMBOL}${amount.toLocaleString()}`, 25, y);
      y += 6;
    });
  y += 10;

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Tasks & Habits", 20, y);
  y += 10;

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(`Tasks Completed: ${data.tasks.completed}/${data.tasks.total}`, 25, y);
  y += 7;
  doc.text(`Focus Time: ${data.focusMinutes} minutes`, 25, y);
  y += 15;

  if (data.habits.length > 0) {
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Habit Performance", 20, y);
    y += 10;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    data.habits.slice(0, 5).forEach((habit) => {
      doc.text(`${habit.name}: ${habit.checkIns} check-ins, ${habit.streak} day streak`, 25, y);
      y += 6;
    });
    y += 10;
  }

  if (data.moods.length > 0) {
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Wellbeing", 20, y);
    y += 10;

    const avgMood = data.moods.reduce((sum, m) => sum + m.mood, 0) / data.moods.length;
    const moodLabels = ["", "Very Low", "Low", "Neutral", "Good", "Great"];

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.text(`Average Mood: ${avgMood.toFixed(1)} (${moodLabels[Math.round(avgMood)]})`, 25, y);
    y += 7;
    doc.text(`Mood Entries: ${data.moods.length}`, 25, y);
    y += 15;
  }

  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(128, 128, 128);
  doc.text("Generated by Pro Vision", pageWidth / 2, doc.internal.pageSize.getHeight() - 15, { align: "center" });
  doc.text(new Date().toLocaleDateString(), pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: "center" });

  return doc.output("blob");
}

export function downloadReport(data: ReportData, filename?: string) {
  const blob = generatePDFReport(data);
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename || `pro-vision-report-${new Date().toISOString().split("T")[0]}.pdf`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
