export { Navbar } from "./Navbar";
export { Hero } from "./Hero";
export { Features } from "./Features";
export { CoachSection } from "./CoachSection";
export { Stats } from "./Stats";
export { WellbeingSection } from "./WellbeingSection";
export { Pricing } from "./Pricing";
export { CTASection } from "./CTASection";
export { Footer } from "./Footer";
