import { type TranslationKey } from "@/i18n/translations";
import {
  Layout,
  ListChecks,
  Target,
  Wallet,
  Timer,
  Newspaper,
  BarChart3,
  Heart,
  Settings,
  Shield,
  Trophy,
  BookOpen,
  Bookmark,
  Coffee,
  Users,
  Moon,
  Dumbbell,
  GraduationCap as GraduationCapIcon,
  Sparkles,
  Award,
  BarChart,
  Sun,
  Brain,
  UserPlus,
  Activity,
  QrCode,
  CreditCard,
} from "lucide-react";

export type NavItem = {
  path: string;
  icon: React.ComponentType<{ className?: string }>;
  labelKey: TranslationKey;
  id: string;
  section?: string;
};

export const NAV_ITEMS: NavItem[] = [
  {
    path: "/dashboard",
    icon: Layout,
    labelKey: "nav.dashboard" as TranslationKey,
    id: "dashboard",
    section: "core",
  },
  {
    path: "/todo",
    icon: ListChecks,
    labelKey: "nav.todo" as TranslationKey,
    id: "todo",
    section: "core",
  },
  {
    path: "/habits",
    icon: Target,
    labelKey: "nav.habits" as TranslationKey,
    id: "habits",
    section: "core",
  },
  {
    path: "/expense",
    icon: Wallet,
    labelKey: "nav.expense" as TranslationKey,
    id: "expense",
    section: "core",
  },
  {
    path: "/focus",
    icon: Timer,
    labelKey: "nav.focus" as TranslationKey,
    id: "focus",
    section: "core",
  },
  {
    path: "/goals",
    icon: Trophy,
    labelKey: "nav.goals" as TranslationKey,
    id: "goals",
    section: "productivity",
  },
  {
    path: "/journal",
    icon: BookOpen,
    labelKey: "nav.journal" as TranslationKey,
    id: "journal",
    section: "productivity",
  },
  {
    path: "/reading",
    icon: Bookmark,
    labelKey: "nav.reading" as TranslationKey,
    id: "reading",
    section: "productivity",
  },
  {
    path: "/study",
    icon: GraduationCapIcon,
    labelKey: "nav.study" as TranslationKey,
    id: "study",
    section: "productivity",
  },
  {
    path: "/learning-paths",
    icon: GraduationCapIcon,
    labelKey: "nav.learningPaths" as TranslationKey,
    id: "learningPaths",
    section: "productivity",
  },
  {
    path: "/fitness",
    icon: Dumbbell,
    labelKey: "nav.fitness" as TranslationKey,
    id: "fitness",
    section: "health",
  },
  {
    path: "/sleep",
    icon: Moon,
    labelKey: "nav.sleep" as TranslationKey,
    id: "sleep",
    section: "health",
  },
  {
    path: "/nutrition",
    icon: Coffee,
    labelKey: "nav.nutrition" as TranslationKey,
    id: "nutrition",
    section: "health",
  },
  {
    path: "/health-dashboard",
    icon: Activity,
    labelKey: "nav.healthDashboard" as TranslationKey,
    id: "healthDashboard",
    section: "health",
  },
  {
    path: "/wellbeing",
    icon: Heart,
    labelKey: "nav.wellbeing" as TranslationKey,
    id: "wellbeing",
    section: "health",
  },
  {
    path: "/checkin",
    icon: Sun,
    labelKey: "nav.checkin" as TranslationKey,
    id: "checkin",
    section: "health",
  },
  {
    path: "/gratitude",
    icon: Sparkles,
    labelKey: "nav.gratitude" as TranslationKey,
    id: "gratitude",
    section: "health",
  },
  {
    path: "/payment",
    icon: CreditCard,
    labelKey: "nav.payment" as TranslationKey,
    id: "payment",
    section: "finance",
  },
  {
    path: "/crm",
    icon: Users,
    labelKey: "nav.crm" as TranslationKey,
    id: "crm",
    section: "social",
  },
  {
    path: "/accountability-partner",
    icon: UserPlus,
    labelKey: "nav.accountabilityPartner" as TranslationKey,
    id: "accountabilityPartner",
    section: "social",
  },
  {
    path: "/challenges",
    icon: Trophy,
    labelKey: "nav.challenges" as TranslationKey,
    id: "challenges",
    section: "social",
  },
  {
    path: "/social-challenges",
    icon: Users,
    labelKey: "nav.socialChallenges" as TranslationKey,
    id: "socialChallenges",
    section: "social",
  },
  {
    path: "/gamification",
    icon: Award,
    labelKey: "nav.gamification" as TranslationKey,
    id: "gamification",
    section: "social",
  },
  {
    path: "/achievements",
    icon: Award,
    labelKey: "nav.achievements" as TranslationKey,
    id: "achievements",
    section: "social",
  },
  {
    path: "/news",
    icon: Newspaper,
    labelKey: "nav.news" as TranslationKey,
    id: "news",
    section: "discover",
  },
  {
    path: "/reports",
    icon: BarChart3,
    labelKey: "nav.reports" as TranslationKey,
    id: "reports",
    section: "discover",
  },
  {
    path: "/heatmap",
    icon: BarChart,
    labelKey: "nav.heatmap" as TranslationKey,
    id: "heatmap",
    section: "discover",
  },
  {
    path: "/correlation",
    icon: Brain,
    labelKey: "nav.correlation" as TranslationKey,
    id: "correlation",
    section: "discover",
  },
  {
    path: "/qr-profile",
    icon: QrCode,
    labelKey: "nav.qrProfile" as TranslationKey,
    id: "qrProfile",
    section: "discover",
  },
  {
    path: "/analytics",
    icon: BarChart,
    labelKey: "nav.analytics" as TranslationKey,
    id: "analytics",
    section: "discover",
  },
  {
    path: "/encryption",
    icon: Shield,
    labelKey: "nav.encryption" as TranslationKey,
    id: "encryption",
    section: "discover",
  },
  {
    path: "/ai-life-coach",
    icon: Brain,
    labelKey: "nav.aiLifeCoach" as TranslationKey,
    id: "aiLifeCoach",
    section: "discover",
  },
  {
    path: "/bill-split",
    icon: Users,
    labelKey: "nav.billSplit" as TranslationKey,
    id: "billSplit",
    section: "finance",
  },
  {
    path: "/subscriptions",
    icon: CreditCard,
    labelKey: "nav.subscriptions" as TranslationKey,
    id: "subscriptions",
    section: "finance",
  },
  {
    path: "/market-prices",
    icon: BarChart3,
    labelKey: "nav.marketPrices" as TranslationKey,
    id: "marketPrices",
    section: "discover",
  },
  {
    path: "/bengali-calendar",
    icon: Sun,
    labelKey: "nav.bengaliCalendar" as TranslationKey,
    id: "bengaliCalendar",
    section: "discover",
  },
  {
    path: "/emergency-sos",
    icon: Shield,
    labelKey: "nav.emergencySOS" as TranslationKey,
    id: "emergencySOS",
    section: "health",
  },
  {
    path: "/carbon-footprint",
    icon: Heart,
    labelKey: "nav.carbonFootprint" as TranslationKey,
    id: "carbonFootprint",
    section: "discover",
  },
  {
    path: "/meal-planning",
    icon: Coffee,
    labelKey: "nav.mealPlanning" as TranslationKey,
    id: "mealPlanning",
    section: "health",
  },
  {
    path: "/commute-tracker",
    icon: Activity,
    labelKey: "nav.commuteTracker" as TranslationKey,
    id: "commuteTracker",
    section: "health",
  },
  {
    path: "/voice-notes",
    icon: BookOpen,
    labelKey: "nav.voiceNotes" as TranslationKey,
    id: "voiceNotes",
    section: "productivity",
  },
  {
    path: "/achievement-sharing",
    icon: Award,
    labelKey: "nav.achievementSharing" as TranslationKey,
    id: "achievementSharing",
    section: "social",
  },
  {
    path: "/daily-streaks",
    icon: Trophy,
    labelKey: "nav.dailyStreaks" as TranslationKey,
    id: "dailyStreaks",
    section: "social",
  },
  {
    path: "/family",
    icon: Users,
    labelKey: "nav.familyDashboard" as TranslationKey,
    id: "familyDashboard",
    section: "social",
  },
  {
    path: "/family-sharing",
    icon: Users,
    labelKey: "nav.familySharing" as TranslationKey,
    id: "familySharing",
    section: "social",
  },
];

export const BOTTOM_NAV = NAV_ITEMS.slice(0, 5);
