 
export const api = {
  users: {
    currentUser: async () => null,
    upsertUser: async (...args) => null,
    listPremiumUsers: async () => [],
  },
  userProfiles: {
    get: async () => null,
    upsert: async (...args) => null,
  },
  tasks: {
    list: async () => [],
    create: async (...args) => null,
    toggle: async (...args) => null,
    remove: async (...args) => null,
    stats: async () => ({ total: 0, completed: 0, pending: 0, overdue: 0 }),
  },
  habits: {
    list: async () => [],
    create: async (...args) => null,
    checkIn: async (...args) => null,
    remove: async (...args) => null,
    stats: async () => ({
      total: 0,
      totalStreak: 0,
      avgRate: 0,
      todayCompleted: 0,
    }),
  },
  wallets: {
    list: async () => [],
    create: async (...args) => null,
    update: async (...args) => null,
    remove: async (...args) => null,
  },
  transactions: {
    list: async () => [],
    create: async (...args) => null,
    remove: async (...args) => null,
    stats: async () => ({
      totalIncome: 0,
      totalExpense: 0,
      balance: 0,
      categories: [],
      thisMonthIncome: 0,
      thisMonthExpense: 0,
    }),
  },
  goals: {
    list: async () => [],
    create: async (...args) => null,
    update: async (...args) => null,
    remove: async (...args) => null,
  },
  focusSessions: {
    list: async () => [],
    create: async (...args) => null,
    stats: async () => ({
      sessions: 0,
      totalMinutes: 0,
      totalHours: 0,
      todayMinutes: 0,
    }),
  },
  moods: {
    list: async () => [],
    create: async (...args) => null,
    stats: async () => ({ moodStreak: 0, todayMood: null, avgMood: 0 }),
  },
  sleepLogs: {
    list: async () => [],
    create: async (...args) => null,
    stats: async () => ({ avgHours: 0, streak: 0, todayHours: 0 }),
  },
  gratitudeEntries: {
    list: async () => [],
    create: async (...args) => null,
    remove: async (...args) => null,
    stats: async () => ({ total: 0, thisWeek: 0 }),
  },
  news: {
    fetchNews: async (...args) => ({ articles: [], source: "demo" }),
  },
  admin: {
    listUsers: async () => [],
    getStats: async () => ({
      totalUsers: 0,
      activeToday: 0,
      totalTasks: 0,
      totalHabits: 0,
      totalTransactions: 0,
    }),
    grantPremium: async (...args) => null,
    revokePremium: async (...args) => null,
    deleteUser: async (...args) => null,
  },
  kanban: {
    list: async () => [],
    createColumn: async (...args) => null,
    updateColumn: async (...args) => null,
    deleteColumn: async (...args) => null,
    createTask: async (...args) => null,
    updateTask: async (...args) => null,
    moveTask: async (...args) => null,
    deleteTask: async (...args) => null,
    initializeDefaultColumns: async () => null,
  },
  waterLogs: {
    listByDate: async (...args) => [],
    getTodayTotal: async () => 0,
    addWater: async (...args) => null,
    removeWater: async (...args) => null,
    getWeeklyStats: async () => ({}),
  },
  recurringTransactions: {
    list: async () => [],
    create: async (...args) => null,
    update: async (...args) => null,
    remove: async (...args) => null,
    processDue: async () => null,
  },
  investments: {
    list: async () => [],
    create: async (...args) => null,
    update: async (...args) => null,
    remove: async (...args) => null,
    stats: async () => ({
      totalInvested: 0,
      totalCurrent: 0,
      totalGainLoss: 0,
    }),
  },
  loans: {
    list: async () => [],
    create: async (...args) => null,
    update: async (...args) => null,
    addPayment: async (...args) => null,
    remove: async (...args) => null,
    stats: async () => ({
      totalGiven: 0,
      totalTaken: 0,
      pendingGiven: 0,
      pendingTaken: 0,
    }),
  },
  automation: {
    listRules: async () => [],
    createRule: async (...args) => null,
    updateRule: async (...args) => null,
    deleteRule: async (...args) => null,
    getSmartSuggestions: async () => [],
  },
  challenges: {
    listChallenges: async () => [],
    create: async (...args) => null,
    join: async (...args) => null,
    leave: async (...args) => null,
    updateProgress: async (...args) => null,
    getLeaderboard: async () => [],
  },
  achievements: {
    listAchievements: async () => [],
    listUserAchievements: async () => [],
    unlockAchievement: async (...args) => null,
    checkAndUnlockAchievements: async () => null,
  },
  insights: {
    getMoodInsights: async () => ({ topMoods: [], averageValue: 0, trend: [] }),
    getHabitInsights: async () => ({
      completionRate: 0,
      bestDay: "",
      topHabits: [],
    }),
  },
  expenseGroups: {
    listGroups: async () => [],
    createGroup: async (...args) => null,
    inviteMember: async (...args) => null,
    addExpense: async (...args) => null,
    settleBalance: async (...args) => null,
    getBalances: async (...args) => [],
    getGroupStats: async (...args) => ({ totalSpent: 0, memberCount: 0 }),
  },
  weeklyReport: {
    sendWeeklyReport: async () => null,
    sendWeeklyReportEmail: async (...args) => null,
  },
  exerciseLogs: {
    list: async () => [],
    create: async (...args) => null,
    stats: async () => ({ totalMinutes: 0, totalCalories: 0, thisWeek: 0 }),
  },
  financialReports: {
    balanceSheet: async (...args) => ({
      asOf: Date.now(),
      assets: {
        total: 0,
        current: 0,
        nonCurrent: 0,
        currentBreakdown: [],
        nonCurrentBreakdown: [],
      },
      liabilities: {
        total: 0,
        current: 0,
        nonCurrent: 0,
        currentBreakdown: [],
        nonCurrentBreakdown: [],
      },
      netWorth: 0,
    }),
    incomeExpense: async (...args) => ({
      summary: {
        totalIncome: 0,
        totalExpense: 0,
        netIncome: 0,
        periodIncome: 0,
        periodExpense: 0,
        periodNet: 0,
        compIncome: 0,
        compExpense: 0,
        compNet: 0,
        yearIncome: 0,
        yearExpense: 0,
        yearNet: 0,
        incomeChange: 0,
        expenseChange: 0,
      },
      period: { selected: "", comparison: "", year: 2025 },
      selectedPeriod: {
        income: { categories: [], total: 0 },
        expense: { categories: [], total: 0 },
      },
      comparisonPeriod: {
        income: { categories: [], total: 0 },
        expense: { categories: [], total: 0 },
      },
    }),
  },
};
export const internal = api;
export default api;
